# Generated by Django 5.2.5 on 2025-08-23 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antibiotic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('lab_type', models.CharField(choices=[('hospital', 'Hospital'), ('research', 'Research'), ('private', 'Private')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacteria_name', models.CharField(max_length=200)),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('sputum', 'Sputum'), ('wound', 'Wound'), ('other', 'Other')], max_length=100)),
                ('test_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolates', to='amr.lab')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('R', 'Resistant'), ('I', 'Intermediate'), ('S', 'Sensitive')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('antibiotic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amr.antibiotic')),
                ('isolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='amr.isolate')),
            ],
            options={
                'unique_together': {('isolate', 'antibiotic')},
            },
        ),
    ]
